name: ect_attendance
description: A new Flutter application for submitting attendance using qr code reader.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: domain

  data:
    path: data

  cupertino_icons: ^1.0.2

  flutter_bloc: ^7.0.0

  firebase_analytics: "^7.0.1"

  paginate_firestore:
    path: plugins/paginate_firestore

  path_provider: ^2.0.2
  qr_code_scanner: ^0.5.1
  qr_flutter: ^4.0.0

  share_plus: ^2.1.2

  datetime_picker_formfield: ^2.0.0

  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter

  syncfusion_flutter_charts: ^19.1.66+1

  file_picker: ^3.0.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

flutter_intl:
  main_locale: en_US
  enabled: true
