name: ect_attendance
description: A new Flutter application for submitting attendance using qr code reader.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  domain:
    path: domain

  data:
    path: data

  cupertino_icons: ^1.0.2

  flutter_bloc: ^7.0.0

  firebase_analytics: "^7.0.1"

  circular_bottom_navigation: ^1.0.1

  path_provider: ^2.0.2
  qr_code_scanner: ^0.5.1
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
